name: Make Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install libgtest-dev libgmock-dev libmosquitto-dev
      - uses: actions/checkout@v3
      - name: build
        run: make
